ShultzeUI/Models/Result/ResultModel.cs
using ShultzeResponse;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShultzeUI.Models.Result
{
    public class ResultModel
    {
        public IEnumerable<Theme> Themes { get; set; }
        public IEnumerable<Option> Options { get; set; }
        public Int32[,] Responses { get; set; }
    }
}

ShultzeUI/Controllers/ResultController.cs
using ShultzeUI.Models.Result;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShultzeUI.Controllers
{
    public class ResultController : Controller
    {
        //
        // GET: /Index/
        private static string connectionString = @"Server=LENOVO-PC\SQLEXPRESS;Database=Shultze; User Id=sa;  Password=su;";

        public ActionResult Index(Int32? id) //nullable Int32!!!1111
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                ResultModel model = new ResultModel();

                if (id.HasValue)
                {
                    model.Responses = ShultzeResponse.ShultzeMethods.ProcessResponses(connection, id.Value);
                    model.Options = ShultzeResponse.ShultzeMethods.GetOptions(connection, id.Value);
                }
                model.Themes = ShultzeResponse.ShultzeMethods.GetThemes(connection);

                return Request.IsAjaxRequest() ? (ActionResult)PartialView("Partial/Table", model) : View("Index", model);
            }
        }
    }
}

ShultzeUI/Views/Result/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@model ShultzeUI.Models.Result.ResultModel

<div class="container">
    <div class="row">
        <div class="col-md-12"></div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>

        <div class="col-md-8">


            @foreach (ShultzeResponse.Theme theme in Model.Themes)
            { 
                <a class="btn btn-default js-reload"  href="@Url.Action("Index", "Result", new { id = theme.ID })">@theme.Name</a>
            }
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="row">
        <div class="col-md-12">
        </div>
    </div>

    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 table-placeholder">
            @if (Model.Responses != null)
            {
                Html.RenderPartial("Partial/Table", Model);
            }
        </div>
        <div class="col-md-2"></div>
    </div>

    <div class="row">
        <div class="col-md-2"><a class="js-vote btn btn-default">VOTE!</a></div>
        <div class="col-md-10"></div>
    </div>
</div>

<div id="dialog">Add Data</div>

@section scripts {
    <script src="~/Scripts/Shultze.js" type="text/javascript"></script>
}

ShultzeUI/Views/Result/Partial/Table.cshtml
@model ShultzeUI.Models.Result.ResultModel           

     <table class="table table-striped table-bordered table-hover table-condensed">
                    <thead>
                        <tr class="success">
                            <th></th>
                            @for (Int32 i = 0; i < Model.Responses.GetLength(0); i++)
                            {
                                <th>@Model.Options.ElementAt(i).Name</th>
                            }
                            <th><span class="js-show">Show</span></th>
                        </tr>
                    </thead>
                    @for (Int32 i = 0; i < Model.Responses.GetLength(0); i++)
                    {
                        <tr>
                            <td>@Model.Options.ElementAt(i).Name
                            </td>
                            @for (Int32 j = 0; j < Model.Responses.GetLength(1); j++)
                            {
                                <td style="text-align: right; padding: 5px;">
                                    @Model.Responses[i, j]
                                </td>
                            }
                            <td>
                                <span class="js-drop">Drop</span>
                            </td>
                        </tr>    
                    }
                </table>

ShultzeUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/themes/base/css")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @RenderSection("scripts", required: false)
</body>
</html>